# Generated by Django 3.2.9 on 2021-11-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quemsomos',
            old_name='descricao3',
            new_name='descricao',
        ),
    ]
