# Generated by Django 3.2.9 on 2021-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20211111_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipemembro',
            name='imagem',
            field=models.ImageField(upload_to='imagens', verbose_name='Primeira imagem'),
        ),
    ]
